<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\Aspire\BookShop.Shared\BookShop.Shared.csproj"/>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Api\BuildingBlocks.Api.csproj" />
        <ProjectReference Include="..\BookShop.Catalog.Application\BookShop.Catalog.Application.csproj"/>
        <ProjectReference Include="..\BookShop.Catalog.Infrastructure\BookShop.Catalog.Infrastructure.csproj" />
    </ItemGroup>
</Project>
