<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Api\BuildingBlocks.Api.csproj" />
        <ProjectReference Include="..\..\Users\BookShop.Users.IntegrationEvents\BookShop.Users.IntegrationEvents.csproj"/>
        <ProjectReference Include="..\BookShop.Cart.Application\BookShop.Cart.Application.csproj"/>
        <ProjectReference Include="..\BookShop.Cart.Infrastructure\BookShop.Cart.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
