<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aspire\BookShop.ServiceDefaults\BookShop.ServiceDefaults.csproj"/>
        <ProjectReference Include="..\Aspire\BookShop.Shared\BookShop.Shared.csproj"/>
        <ProjectReference Include="..\BuildingBlocks\BuildingBlocks.Api\BuildingBlocks.Api.csproj"/>
        <ProjectReference Include="..\Services\Cart\BookShop.Cart.Api\BookShop.Cart.Api.csproj"/>
        <ProjectReference Include="..\Services\Catalog\BookShop.Catalog.Api\BookShop.Catalog.Api.csproj"/>
        <ProjectReference Include="..\Services\Users\BookShop.Users.Api\BookShop.Users.Api.csproj"/>
    </ItemGroup>

</Project>
