// <auto-generated />

#nullable disable

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace BookShop.Catalog.Infrastructure.EntityFramework.Migrations;

[DbContext(typeof(CatalogDbContext))]
internal class CatalogDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("catalog")
            .HasAnnotation("ProductVersion", "10.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("BookShop.Catalog.Domain.Categories.Category", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("name");

            b.HasKey("Id")
                .HasName("pk_categories");

            b.HasIndex("Name")
                .IsUnique()
                .HasDatabaseName("ix_categories_name");

            b.ToTable("categories", "catalog");
        });
#pragma warning restore 612, 618
    }
}
